import type {
  Certification,
  Experience,
  Profile,
  Project,
  ProjectArtifact,
  ProjectCategory,
  Skill,
  SkillEdge,
  Testimonial,
} from "./types";

function stubProject({
  id,
  slug,
  title,
  client,
  categories,
  cover_url,
  sort,
  summary,
}: {
  id: string;
  slug: string;
  title: string;
  client: string;
  categories: ProjectCategory[];
  cover_url: string | null;
  sort: number;
  summary: string;
}): Project {
  return {
    id,
    slug,
    title,
    client,
    categories,
    cover_url,
    sort,
    summary,
    company_url: null,
    role: "UX Designer",
    platforms: [],
    published: true,
    brief: null,
    problem: null,
    methodologies: [],
    technologies: [],
    leadership: null,
    impact_metrics: [],
  };
}

export const profile: Profile = {
  name: "David Obando Reyes",
  title: "UX Engineer",
  bio: "Senior UX/UI & Product Designer crafting digital products end-to-end—from research and strategy to interaction design, design systems, and AI-powered experiences. Exploring how agentic AI can transform the way we design, build, and use digital products. Based in Cali, Colombia.",
  email: "davinciobandoreyes@gmail.com",
  location: "Cali, Valle del Cauca, Colombia",
  links: {
    linkedin: "https://www.linkedin.com/in/davidobandor/",
    cv_path: "/david-obando-reyes-cv.pdf",
    behance: "https://www.behance.net/davidobandor/",
    medium:
      "https://medium.com/@davinciobandoreyes/from-laid-off-to-landing-interviews-a-product-designers-playbook-for-2026-7b04b65c60fe",
  },
  languages: [
    "Spanish (Native)",
    "English (Advanced / Bilingual)",
    "Japanese (Basic)",
  ],
  highlights: [
    { value: "10+", label: "Years of experience" },
    { value: "6+", label: "Industries" },
    { value: "Multi-disciplinary", label: "Product Manager, gamification, and Ai product design" },
  ],
};

export const projects: Project[] = [
  {
    id: "p-yourway",
    slug: "yourway",
    title: "Student engagement experience",
    client: "Yourway Learning",
    company_url: "https://www.yourwaylearning.com/",
    role: "Senior UX Designer & Product Manager",
    summary:
      "Leading product strategy and UX for teacher- and student-facing learning experiences.",
    categories: ["edutech", "ai"],
    platforms: ["Desktop", "Mobile"],
    cover_url: "/work/yourway.jpg",
    sort: 1,
    published: true,
    brief:
      "Own the end-to-end product development of digital learning experiences — aligning design, engineering, and business goals around student engagement.",
    problem:
      "Complex learning needs had to become intuitive teacher and student products, with clear prioritization and engineering-ready requirements.",
    methodologies: [
      "User research",
      "Product strategy & roadmapping",
      "Agile / Scrum",
      "PRDs & user stories",
      "Agentic AI-assisted ideation",
    ],
    technologies: ["Figma", "Claude", "Cursor AI"],
    leadership:
      "Grew from UX design into product management ownership — shaping strategy, prioritizing opportunities, defining requirements, and partnering with engineering from concept through delivery.",
    impact_metrics: [
      {
        label: "Ownership",
        value: "End-to-end PM + UX",
        note: "Strategy, requirements, and engineering partnership",
      },
      {
        label: "Workflow",
        value: "AI-accelerated design",
        note: "Integrated Claude into ideation and product workflows",
      },
    ],
  },
  stubProject({
    id: "p-everglades",
    slug: "everglades",
    title: "Everglades learning experience",
    client: "Everglades",
    categories: ["edutech"],
    cover_url: "/work/everglades.jpg",
    sort: 2,
    summary: "Educational product UX for the Everglades learning program.",
  }),
  stubProject({
    id: "p-comed",
    slug: "comed",
    title: "ComEd learning experience",
    client: "ComEd",
    categories: ["edutech"],
    cover_url: "/work/comed.jpg",
    sort: 3,
    summary: "Edutech UX for ComEd community and learning experiences.",
  }),
  stubProject({
    id: "p-sympt",
    slug: "sympt",
    title: "Sympt",
    client: "Sympt",
    categories: ["healthtech"],
    cover_url: "/work/sympt.jpg",
    sort: 4,
    summary: "Health-tech product UX for symptom-related patient experiences.",
  }),
  stubProject({
    id: "p-mypearlflow",
    slug: "mypearlflow",
    title: "MyPearl Flow",
    client: "MyPearl Flow",
    categories: ["healthtech", "ai"],
    cover_url: null,
    sort: 5,
    summary: "Health-tech and AI-assisted product UX for MyPearl Flow.",
  }),
  stubProject({
    id: "p-healthbit",
    slug: "healthbit",
    title: "Health Bit",
    client: "Health Bit",
    categories: ["healthtech", "ai"],
    cover_url: null,
    sort: 6,
    summary: "Health-tech product UX with AI-assisted workflows for Health Bit.",
  }),
  stubProject({
    id: "p-wargo",
    slug: "wargo",
    title: "Wargo",
    client: "Wargo",
    categories: ["healthtech"],
    cover_url: "/work/wargo.jpg",
    sort: 7,
    summary: "Health-tech product UX for Wargo.",
  }),
  stubProject({
    id: "p-budgee",
    slug: "budgee",
    title: "Budgee",
    client: "Budgee",
    categories: ["fintech"],
    cover_url: "/work/budgee.jpg",
    sort: 8,
    summary: "Fintech product UX for Budgee.",
  }),
  stubProject({
    id: "p-bankee",
    slug: "bankee",
    title: "Bankee",
    client: "Bankee",
    categories: ["fintech", "use-cases"],
    cover_url: null,
    sort: 9,
    summary: "Fintech UX and use-case design for Bankee.",
  }),
  {
    id: "p-mibanco",
    slug: "mibanco",
    title: "Fintech design system & UX",
    client: "MiBanco (via Encora)",
    company_url: null,
    role: "Senior UX/UI Designer",
    summary:
      "Research-led UX for web and mobile, plus the company’s first design system and DesignOps practices.",
    categories: ["fintech"],
    platforms: ["Desktop", "Mobile"],
    cover_url: "/work/mibanco.jpg",
    sort: 10,
    published: true,
    brief:
      "Improve digital banking experiences for web and mobile while establishing shared design foundations.",
    problem:
      "Product decisions lacked a shared research foundation and a reusable design system, slowing delivery and consistency.",
    methodologies: [
      "User research",
      "Affinity mapping",
      "User journeys",
      "Personas",
      "Low-fidelity prototyping",
      "DesignOps",
      "Agile",
    ],
    technologies: ["Figma", "InVision"],
    leadership:
      "Developed the company’s first design system and introduced DesignOps practices to improve team performance.",
    impact_metrics: [
      {
        label: "Foundation",
        value: "First design system",
        note: "Established shared UI foundations for web and mobile",
      },
      {
        label: "Ops",
        value: "DesignOps introduced",
        note: "Integrated Agile practices to improve team performance",
      },
    ],
  },
  stubProject({
    id: "p-fortnite-preset",
    slug: "fortnite-preset",
    title: "Fortnite Preset improvement",
    client: "Fortnite — Epic Games (via Globant)",
    categories: ["gaming"],
    cover_url: null,
    sort: 11,
    summary: "UX improvement for Fortnite preset flows across platforms.",
  }),
  {
    id: "p-fortnite",
    slug: "fortnite-locker",
    title: "In-game Locker redesign",
    client: "Fortnite — Epic Games (via Globant)",
    company_url: "https://www.fortnite.com/",
    role: "Senior UX Designer",
    summary:
      "Redesigned the Fortnite Locker across console, PC, and mobile to improve returning-user engagement.",
    categories: ["gaming"],
    platforms: [
      "Desktop",
      "Nintendo Switch",
      "PlayStation",
      "Xbox",
      "Mobile",
    ],
    cover_url: "/work/fortnite-locker.jpg",
    sort: 12,
    published: true,
    brief:
      "Redesign the in-game Locker experience for Fortnite players across multiple interaction environments.",
    problem:
      "Returning players needed a clearer, more engaging Locker that increased adoption of key features without breaking multi-platform interaction patterns.",
    methodologies: [
      "User research",
      "Competitive benchmarking",
      "Customer journeys",
      "User flows",
      "Playtesting",
    ],
    technologies: ["Figma", "Unreal Engine", "UserTesting"],
    leadership: null,
    impact_metrics: [
      {
        label: "Engagement",
        value: "↑ returning users",
        note: "Improved adoption of key Locker features",
      },
      {
        label: "Platforms",
        value: "5 platforms",
        note: "Desktop, Switch, PlayStation, Xbox, Mobile",
      },
    ],
  },
  stubProject({
    id: "p-pokemon-unite",
    slug: "pokemon-unite",
    title: "Pokemon Unite",
    client: "Pokemon Unite",
    categories: ["use-cases"],
    cover_url: null,
    sort: 13,
    summary: "Use-case UX for Pokemon Unite.",
  }),
  stubProject({
    id: "p-truckers-networks",
    slug: "truckers-networks",
    title: "Truckers Networks",
    client: "Truckers Networks",
    categories: ["automotive"],
    cover_url: "/work/truckers-networks.jpg",
    sort: 14,
    summary: "Automotive network experience connecting truckers and operators.",
  }),
  {
    id: "p-notiplac",
    slug: "notiplac",
    title: "After-sales loyalty platform",
    client: "Notiplac — Boken SAS",
    company_url: null,
    role: "Product Designer",
    summary:
      "Automotive mobile and web app that lifted retention and saved managers an hour a day.",
    categories: ["automotive"],
    platforms: ["Mobile", "Web"],
    cover_url: "/work/notiplac.jpg",
    sort: 15,
    published: true,
    brief:
      "Lead UX for Notiplac — an automotive mobile and web app designed to boost customer loyalty in after-sales service while streamlining daily operations.",
    problem:
      "Dealerships struggled with after-sales churn and time-consuming internal workflows for car managers.",
    methodologies: [
      "UX research",
      "Product design",
      "Workflow optimization",
    ],
    technologies: ["Figma"],
    leadership: "Led UX efforts from concept through measurable client outcomes.",
    impact_metrics: [
      {
        label: "Retention",
        value: "+7.5%",
        note: "Exceeded the client’s 2% churn-reduction target for most clients",
      },
      {
        label: "Time saved",
        value: "~1 hour / day",
        note: "Optimized workflows for car managers",
      },
    ],
  },
  stubProject({
    id: "p-coral-todo",
    slug: "coral-todo",
    title: "Coral Todo",
    client: "Coral Todo",
    categories: ["ai"],
    cover_url: "/work/coral-todo.jpg",
    sort: 16,
    summary: "AI-assisted todo product UX for Coral Todo.",
  }),
  {
    id: "p-160",
    slug: "160-drivers-academy",
    title: "Driver & instructor apps",
    client: "160 Drivers Academy (via Globant)",
    company_url: null,
    role: "Senior UX Designer",
    summary:
      "Led research, design system, and usability testing for automotive learning apps.",
    categories: ["automotive"],
    platforms: ["Desktop", "Mobile"],
    cover_url: null,
    sort: 99,
    published: false,
    brief:
      "Design driver and instructor experiences for an automotive academy product suite.",
    problem:
      "Drivers and instructors needed clearer flows and a consistent system to complete training tasks with less friction.",
    methodologies: [
      "User research",
      "Personas",
      "Customer journeys",
      "User flows",
      "Usability testing (Maze)",
      "Agile",
    ],
    technologies: ["Figma", "Maze"],
    leadership:
      "Led the design team in an Agile environment and partnered with the Project Manager on product planning.",
    impact_metrics: [
      {
        label: "System",
        value: "Design system shipped",
        note: "Built the product’s design system in Figma",
      },
      {
        label: "Validation",
        value: "Maze usability tests",
        note: "Improved driver and instructor app usability",
      },
    ],
  },
];

export const projectArtifacts: ProjectArtifact[] = [
  {
    id: "a1",
    project_id: "p-fortnite",
    type: "ux_artifact",
    title: "Competitive benchmarking & journeys",
    body: "Mapped competitive Locker patterns and customer journeys to ground the redesign in player behavior.",
    image_url: null,
    sort: 1,
  },
  {
    id: "a2",
    project_id: "p-fortnite",
    type: "user_flow",
    title: "Multi-platform Locker flows",
    body: "User flows covering Desktop, Switch, PlayStation, Xbox, and Mobile interaction environments.",
    image_url: null,
    sort: 2,
  },
  {
    id: "a3",
    project_id: "p-mibanco",
    type: "ux_artifact",
    title: "Affinity mapping & personas",
    body: "Research synthesis informing journeys and design decisions for web and mobile banking.",
    image_url: null,
    sort: 1,
  },
  {
    id: "a4",
    project_id: "p-mibanco",
    type: "low_fi",
    title: "Low-fidelity prototypes",
    body: "Early InVision and Figma prototypes used to validate structure before high-fidelity work.",
    image_url: null,
    sort: 2,
  },
  {
    id: "a5",
    project_id: "p-160",
    type: "ux_artifact",
    title: "Personas & journeys",
    body: "Driver and instructor personas guiding product decisions across the academy apps.",
    image_url: null,
    sort: 1,
  },
  {
    id: "a6",
    project_id: "p-notiplac",
    type: "user_journey",
    title: "After-sales loyalty journey",
    body: "Journey focused on retention touchpoints and operational efficiency for dealership teams.",
    image_url: null,
    sort: 1,
  },
];

export const experiences: Experience[] = [
  {
    id: "e1",
    company: "Yourway Learning",
    role: "Senior UX Designer & Product Manager",
    dates: "Aug 2024 – Present",
    location: "United States (remote)",
    bullets: [
      "Directed product strategy and roadmap planning across cross-functional teams.",
      "Owned user research, wireframing, and prototyping for validated product decisions.",
      "Authored PRDs and user stories for clear engineering handoff.",
      "Integrated agentic AI (Claude) into the design process to accelerate ideation and workflows.",
    ],
    sort: 1,
  },
  {
    id: "e2",
    company: "Globant",
    role: "Senior UX Designer",
    dates: "2022 – 2025",
    location: "Colombia",
    bullets: [
      "Fortnite (Epic Games): redesigned the in-game Locker; prototyped in Figma and Unreal; playtested with UserTesting.",
      "160 Drivers Academy: led research, design system, Maze usability tests, and design-team leadership in Agile.",
    ],
    sort: 2,
  },
  {
    id: "e3",
    company: "Encora",
    role: "Senior UX/UI Designer",
    dates: "2021 – 2022",
    location: "Colombia",
    bullets: [
      "MiBanco: research, journeys, personas, low-fi prototypes, and the company’s first design system + DesignOps.",
      "Also delivered research and testing across eDoula, Amazon, and eWallet projects.",
    ],
    sort: 3,
  },
  {
    id: "e4",
    company: "Boken SAS",
    role: "Product Designer",
    dates: "2014 – 2021",
    location: "Colombia",
    bullets: [
      "Led UX for Notiplac — automotive loyalty and operations product for after-sales service.",
      "Drove retention above the client’s 2% target (+7.5%) and saved managers up to an hour per day.",
    ],
    sort: 4,
  },
];

export const skills: Skill[] = [
  // UX Research branch
  {
    id: "s-ux",
    name: "UX Research",
    branch: "UX Research",
    level: 1,
    description: "Root of discovery — framing questions and learning from users.",
    related_project_slugs: ["fortnite-locker", "truckers-networks", "mibanco"],
    x: 18,
    y: 22,
  },
  {
    id: "s-testing",
    name: "User Testing",
    branch: "UX Research",
    level: 2,
    description: "Playtests, Maze, and UserTesting to validate decisions early.",
    related_project_slugs: ["fortnite-locker", "truckers-networks"],
    x: 12,
    y: 42,
  },
  {
    id: "s-personas",
    name: "Personas",
    branch: "UX Research",
    level: 2,
    description: "Synthesizing research into actionable user models.",
    related_project_slugs: ["truckers-networks", "mibanco"],
    x: 24,
    y: 42,
  },
  {
    id: "s-journeys",
    name: "Journeys",
    branch: "UX Research",
    level: 3,
    description: "End-to-end customer journeys that expose friction and opportunity.",
    related_project_slugs: ["fortnite-locker", "mibanco", "notiplac"],
    x: 18,
    y: 62,
  },
  // Product branch
  {
    id: "s-product",
    name: "Product Strategy",
    branch: "Product",
    level: 1,
    description: "Aligning design, engineering, and business around outcomes.",
    related_project_slugs: ["yourway"],
    x: 50,
    y: 18,
  },
  {
    id: "s-roadmap",
    name: "Roadmapping",
    branch: "Product",
    level: 2,
    description: "Sequencing opportunities into a clear product path.",
    related_project_slugs: ["yourway"],
    x: 42,
    y: 38,
  },
  {
    id: "s-prds",
    name: "PRDs & Stories",
    branch: "Product",
    level: 2,
    description: "Engineering-ready requirements and user stories.",
    related_project_slugs: ["yourway"],
    x: 58,
    y: 38,
  },
  {
    id: "s-agile",
    name: "Agile / Scrum",
    branch: "Product",
    level: 3,
    description: "Shipping iteratively with cross-functional teams.",
    related_project_slugs: ["yourway", "truckers-networks", "mibanco"],
    x: 50,
    y: 58,
  },
  // Design Craft
  {
    id: "s-figma",
    name: "Figma",
    branch: "Design Craft",
    level: 1,
    description: "Primary craft tool for systems, flows, and prototypes.",
    related_project_slugs: [
      "fortnite-locker",
      "truckers-networks",
      "mibanco",
      "yourway",
    ],
    x: 78,
    y: 20,
  },
  {
    id: "s-proto",
    name: "Prototyping",
    branch: "Design Craft",
    level: 2,
    description: "Low-fi to hi-fi prototypes that make ideas testable.",
    related_project_slugs: ["fortnite-locker", "mibanco"],
    x: 72,
    y: 40,
  },
  {
    id: "s-systems",
    name: "Design Systems",
    branch: "Design Craft",
    level: 2,
    description: "Reusable foundations — components, tokens, DesignOps.",
    related_project_slugs: ["truckers-networks", "mibanco"],
    x: 84,
    y: 40,
  },
  {
    id: "s-wire",
    name: "Wireframing",
    branch: "Design Craft",
    level: 3,
    description: "Structure before polish — clarifying information and flows.",
    related_project_slugs: ["yourway", "mibanco"],
    x: 78,
    y: 60,
  },
  // AI & Eng
  {
    id: "s-ai",
    name: "Agentic AI Design",
    branch: "AI & Eng",
    level: 1,
    description: "Using Claude and Cursor to accelerate ideation and workflows.",
    related_project_slugs: ["yourway"],
    x: 30,
    y: 78,
  },
  {
    id: "s-cursor",
    name: "Cursor / Claude",
    branch: "AI & Eng",
    level: 2,
    description: "AI-assisted product and design production loops.",
    related_project_slugs: ["yourway"],
    x: 22,
    y: 92,
  },
  {
    id: "s-handoff",
    name: "Eng Handoff",
    branch: "AI & Eng",
    level: 2,
    description: "Clear specs, stories, and collaboration with engineering.",
    related_project_slugs: ["yourway", "fortnite-locker"],
    x: 38,
    y: 92,
  },
  // Games
  {
    id: "s-game",
    name: "Game Design",
    branch: "Games",
    level: 1,
    description: "UX methods applied to games and gamified products.",
    related_project_slugs: ["fortnite-locker"],
    x: 68,
    y: 78,
  },
  {
    id: "s-unreal",
    name: "Unity / Unreal",
    branch: "Games",
    level: 2,
    description: "Prototyping and UI craft inside real-time engines.",
    related_project_slugs: ["fortnite-locker"],
    x: 62,
    y: 92,
  },
  {
    id: "s-play",
    name: "Playtesting",
    branch: "Games",
    level: 2,
    description: "Validating game UX with real player feedback loops.",
    related_project_slugs: ["fortnite-locker"],
    x: 74,
    y: 92,
  },
];

export const skillEdges: SkillEdge[] = [
  { parent_id: "s-ux", child_id: "s-testing" },
  { parent_id: "s-ux", child_id: "s-personas" },
  { parent_id: "s-testing", child_id: "s-journeys" },
  { parent_id: "s-personas", child_id: "s-journeys" },
  { parent_id: "s-product", child_id: "s-roadmap" },
  { parent_id: "s-product", child_id: "s-prds" },
  { parent_id: "s-roadmap", child_id: "s-agile" },
  { parent_id: "s-prds", child_id: "s-agile" },
  { parent_id: "s-figma", child_id: "s-proto" },
  { parent_id: "s-figma", child_id: "s-systems" },
  { parent_id: "s-proto", child_id: "s-wire" },
  { parent_id: "s-systems", child_id: "s-wire" },
  { parent_id: "s-ai", child_id: "s-cursor" },
  { parent_id: "s-ai", child_id: "s-handoff" },
  { parent_id: "s-game", child_id: "s-unreal" },
  { parent_id: "s-game", child_id: "s-play" },
];

export const certifications: Certification[] = [
  {
    id: "c1",
    name: "Introduction to UX Writing",
    issuer: "Domestika",
    issued_at: "2022-09",
    credential_id: "d36a5d7ad755382a96162b3c099ab03f",
  },
  {
    id: "c2",
    name: "Introduction to UX Design",
    issuer: "Domestika",
    issued_at: "2020-11",
    credential_id: "5a7ac0d89f7aca59914851a11a1b8d3d",
  },
  {
    id: "c3",
    name: "Unreal Engine: Foundation Course For UI Artists",
    issuer: "Globant",
    issued_at: "2024-02",
    credential_id: null,
  },
  {
    id: "c4",
    name: "Video Game Production Using UX Methods",
    issuer: "Domestika",
    issued_at: "2023-10",
    credential_id: "ac07f4f202458a98a4f2014f39c41336",
  },
  {
    id: "c5",
    name: "Lean UX",
    issuer: "Certification",
    issued_at: "2020",
    credential_id: null,
  },
  {
    id: "c6",
    name: "Video Game Design",
    issuer: "Certification",
    issued_at: "2023",
    credential_id: null,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    quote:
      "I had the pleasure of working closely with David as he grew from a UX designer into a highly capable product manager. He initially joined our team designing teacher- and student-facing experiences, where he consistently brought strong user empathy, thoughtful design judgment, and a practical understanding of how to turn complex needs into intuitive products. Over time, David expanded his responsibilities beyond design and took ownership of our student engagement experience, helping shape product strategy, prioritize opportunities, define requirements, and collaborate closely with engineering from concept through delivery.\n\nWhat stands out most about David, though, is the kind of teammate he is. He is exceptionally dedicated and reliable. David is a person you can trust to follow through, support the team, and keep moving the work forward even when the path is not straightforward. He approaches challenges with humility and curiosity and is constantly looking for opportunities to learn, improve his craft, and broaden the value he can provide.\n\nDavid’s evolution from UX designer to product manager reflects both his versatility and his commitment to growth. He would be a tremendous addition to any team looking for someone who combines product thinking, design expertise, a strong work ethic, and genuine care for both users and colleagues.",
    author: "Hollin Wakefield",
    role: "Chief Product and Technology Officer",
    company: "Yourway Learning",
  },
  {
    id: "t2",
    quote:
      "I had the opportunity to work with David at Yourway and see how he grew from a very strong UX Designer into a Product Manager. One of his biggest strengths is how he combines both perspectives, always understanding the users while also keeping the business needs in mind. David brings a lot of value to product conversations and has a great ability to connect design, product, and strategy in a very thoughtful way. I'm sure he'll make a great impact wherever he goes.",
    author: "Belén Gudiño",
    role: "Senior Product Manager",
    company: "Yourway Learning",
  },
  {
    id: "t3",
    quote:
      "David is an extremely professional, highly talented Product Designer. I had the honor to work with him on numerous initiatives... and his knowledge about UX, Gamification and Vibecoding is one of a kind. I also had the privilege to see his transition from product into a Leadership role where he shined as a sawvy, collaborative and hands-on leader.",
    author: "Luis Alvarez",
    role: "Product Designer",
    company: "Yourway Learning",
  },
  {
    id: "t4",
    quote:
      "I’ve had the opportunity to work with David, and I can confidently say he is someone who truly pushes things forward. As a designer, he is highly versatile and always willing to support the team, even contributing across different areas. This has given him a holistic understanding of product development.",
    author: "Andrés Quevedo",
    role: "Co-founder",
    company: "Boken",
  },
  {
    id: "t5",
    quote:
      "I’ve had the privilege of working alongside David for nearly three years in game development, serving as his Producer.\n\nHe stands out as one of the most talented and professional UX designers I’ve had the pleasure of collaborating with.\n\nDavid brings deep expertise across the entire UX/UI design workflow—from ideation to implementation—on gaming projects spanning console, PC, and mobile platforms.\n\nHis passion for design is evident in everything he does, and his approach is consistently data-driven, seamlessly integrating insights from UX research, product teams, analytics, and user behavior.\n\nWhat truly sets David apart is his independence and proactive mindset. He excels in cross-functional collaboration, consistently delivering high-quality mockups, wireframes, prototypes, and documentation that supports development from early stages through to release.\n\nHis adaptability and openness to feedback, even during late-stage changes, makes him an invaluable team member.\n\nDavid is a true talent in the UX space, and any team would be lucky to have him.",
    author: "Matias Manzano",
    role: "Producer",
    company: "Globant",
  },
  {
    id: "t6",
    quote:
      "David has been a great asset to the redesign of Truckers Network. He is a multi-talented Senior UX designers who brings great insight to the customer experience.\n\nDavid's advanced knowledge of Figma helped us implement many intuitive designs into our service offering. David guided the team to seamlessly integrate his Figma designs into our Telerik development platform with minimal effort from development, enabling us to completely change the look and feel of our application with a push of a button. This saved us countless man-hours contributing to faster time-to-market deliverables.\n\nDavid's organizational skills helped us establish design template guidelines that assisted development in producing consistent user interface workflows. David's listening skills and patience compliments his energy and enthusiasm, working with David is both effective and enjoyable.\n\nI would highly recommend David for any UX Design position, I'm confident that David will deliver beyond your expectations.",
    author: "James Edgell",
    role: "CTO",
    company: "Truckers Network",
  },
];

export const education = {
  degree: "Bachelor's Degree, Interactive Media Design",
  school: "Universidad ICESI",
  years: "2009 – 2014",
  note: "Human interaction design with foundations in coding (Java, JavaScript, Processing, Swift) plus UX research, writing, and interface design.",
};
